### PR TITLE
Add default mappings for types. Change visibility to public for mappings to allow compiled ef contexts

### LINKED ISSUE #39: Support for compiled models
Looks like EF Core needs a few extra internal fields now - would you accept a PR that adds them?
Very similar to https://github.com/npgsql/efcore.pg/issues/2871

### PR DESCRIPTION
**Pull request by evolvedlight**
This fixes #39 
I tried where possible to match the postgres driver syntax and the recommended MSSQL field names for defaults

### CODE REVIEW

**Comment by StevenRasmussen** [comment]
Thanks for submitting this! Is there a unit test that you could add to verify this functionality?

**Comment by evolvedlight** [comment]
Sure, will take a look later today

**Comment by evolvedlight** [comment]
Hey, I added some tests here - it's not 100% possible to verify the compiled mode perfectly but hopefully this matches what is useful

**Comment by evolvedlight** [comment]
Did you manage to get time to check this? It's currently blocking an upgrade to .Net 8 and I'd prefer to not use my fork. Thanks!

**Comment by StevenRasmussen** [comment]
Looks good!  Thanks!

**Pull request merged**
